'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Script from 'next/script';
import Link from 'next/link';
import { useApp } from './provider';
import { DEMO,clinic,services,brands,formatDate,instructions } from '@/lib/config';
import { validateBooking,slotTaken } from '@/lib/validation';
import { calendarFile,googleCalendar,outlookCalendar,downloadFile } from '@/lib/calendar';
import { Header,Footer,Button,Field,Gift,Icon,Notice,Loading,Referral } from './ui';
function Captcha({onToken}){const el=useRef(null),[loaded,setLoaded]=useState(false);useEffect(()=>{if(!loaded||!el.current||!window.turnstile)return;const id=window.turnstile.render(el.current,{sitekey:process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,action:'booking',callback:onToken,'expired-callback':()=>onToken('')});return()=>window.turnstile?.remove(id);},[loaded]);return <><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" onReady={()=>setLoaded(true)}/><div ref={el}/></>;}
export default function BookingFlow(){
  const params=useSearchParams(),slug=params.get('affiliate'),{data,ready,book}=useApp();const [affiliate,setAffiliate]=useState(null),[slots,setSlots]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[step,setStep]=useState(0),[service,setService]=useState(params.get('service')||''),[day,setDay]=useState(''),[start,setStart]=useState(''),[week,setWeek]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState(null),[captcha,setCaptcha]=useState(''),[captchaKey,setCaptchaKey]=useState(0),[details,setDetails]=useState({name:'',email:'',phone:'',firstVisit:'',insurance:'',policy:'',brands:'',smsConsent:false,website:''});const titleRef=useRef(null);
  useEffect(()=>{if(DEMO){if(!ready)return;const a=slug?data.affiliates.find(a=>a.slug===slug&&a.active):null;if(slug&&!a){setLoadError('This referral is unavailable. You can book directly instead.');setLoading(false);return;}setAffiliate(a);setSlots(data.slots.filter(s=>new Date(s.start)>new Date()&&!slotTaken(s,data.bookings)));setLoading(false);}else{fetch('/api/availability'+(slug?'?affiliate='+encodeURIComponent(slug):'')).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setAffiliate(d.affiliate);setSlots(d.slots);}).catch(e=>setLoadError(e.message)).finally(()=>setLoading(false));}},[ready,slug,data]);
  useEffect(()=>{titleRef.current?.focus();},[step]);
  const dayKey=iso=>new Intl.DateTimeFormat('en-CA',{timeZone:clinic.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso));
  const days=useMemo(()=>[...new Map(slots.map(s=>[dayKey(s.start),s.start])).entries()], [slots]);
  const visibleDays=days.filter(([,iso])=>{const diff=(new Date(iso)-new Date())/86400000;return diff>=week*7&&diff<(week+1)*7;});
  function change(key,value){setDetails(d=>({...d,[key]:value}));}
  function next(){setError('');if(step===0&&!services.some(s=>s.id===service)){setError('Choose the care you need.');return;}if(step===1&&!start){setError('Choose a date and available time.');return;}setStep(s=>s+1);}
  async function submit(e){e.preventDefault();setError('');setBusy(true);try{const payload=validateBooking({...details,firstVisit:details.firstVisit==='yes'?true:details.firstVisit==='no'?false:null,service,start,affiliateId:affiliate?.id});if(!DEMO&&!captcha)throw new Error('Complete the verification before booking.');const result=await book({...payload,captcha,website:details.website});setConfirmation(result);setStep(3);}catch(e){setError(e.message);setCaptcha('');setCaptchaKey(k=>k+1);}finally{setBusy(false);}}
  if(loading)return <Loading/>;
  if(loadError)return <><Header/><main className="container empty-page" id="main-content"><h1>Arrange your visit</h1><Notice error>{loadError}</Notice>{slug?<Button href="/booking">Book directly</Button>:<Button onClick={()=>window.location.reload()}>Try again</Button>}</main><Footer/></>;
  const labels=['Service','Date & time','Your details','Confirmation'];
  return <><Header bookingHref={affiliate?'/book/'+affiliate.slug:'/'} bookingLabel="Back to Eyecon"/><main className="booking-shell" id="main-content"><aside className="booking-aside"><p className="eyebrow">YOUR EYECON VISIT</p><h1>A little time.<br/><em>A clearer view.</em></h1><p>Choose your appointment, find a time that suits you, and we’ll look forward to welcoming you.</p>{affiliate&&<><Referral affiliate={affiliate}/><Gift compact/></>}<div className="booking-help"><Icon name="phone"/><h3>Prefer a conversation?</h3>{clinic.phone?<a href={'tel:'+clinic.phone}>{clinic.phone}</a>:<p>Clinic phone details will be added before launch.</p>}</div></aside><section className="booking-panel">{affiliate&&<p className="booking-ref">Booking through <strong>{affiliate.name}</strong></p>}<ol className="stepper" aria-label="Booking progress">{labels.map((label,i)=><li key={label} aria-current={i===step?'step':undefined} className={i<=step?'current':''}><span>{i<step?<Icon name="check" size={15}/>:i+1}</span><small>{label}</small></li>)}</ol><h2 ref={titleRef} tabIndex={-1}>{['What would you like to book?','Choose a time','Your details','You’re booked'][step]}</h2><Notice error>{error}</Notice>
  {step===0&&<><div className="service-choices" role="radiogroup" aria-label="Appointment type">{services.map(s=><label key={s.id} className={`service-choice ${service===s.id?'selected':''}`}><input type="radio" name="service" value={s.id} checked={service===s.id} onChange={()=>setService(s.id)}/><Icon name={s.icon}/><span><strong>{s.name}</strong><small>{s.description}</small></span></label>)}</div><div className="urgent-note">Urgent eye concern? {clinic.phone?<a href={'tel:'+clinic.phone}>Call the clinic</a>:<span>Please contact the clinic for guidance.</span>}</div><div className="form-actions"><Button onClick={next}>Continue</Button></div></>}
  {step===1&&<><p className="muted">{services.find(s=>s.id===service)?.name} · Times shown in {clinic.timezone.replace('_',' ')}.</p>{!slots.length?<Notice>No online times are available. Please contact the clinic or check back later.</Notice>:<><div className="week-tabs" aria-label="Date range">{['Next 7 days','Following week','Weeks 3–4','Later'].map((t,i)=><button key={t} className={week===i?'active':''} onClick={()=>{setWeek(i);setDay('');setStart('');}}>{t}</button>)}</div><div className="day-grid" role="group" aria-label="Available days">{(week===2?days.filter(([,iso])=>{let d=(new Date(iso)-new Date())/86400000;return d>=14&&d<28;}):week===3?days.filter(([,iso])=>(new Date(iso)-new Date())/86400000>=28):visibleDays).map(([key,iso])=><button key={key} className={day===key?'active':''} aria-pressed={day===key} onClick={()=>{setDay(key);setStart('');}}><small>{formatDate(iso,{dateStyle:undefined,timeStyle:undefined,weekday:'short'})}</small>{formatDate(iso,{dateStyle:undefined,timeStyle:undefined,month:'short',day:'numeric'})}</button>)}</div>{!day&&<p className="quiet">Select a day to see appointment times.</p>}<div className="time-grid" role="group" aria-label="Available times">{slots.filter(s=>dayKey(s.start)===day).map(s=><button key={s.start} aria-pressed={start===s.start} className={start===s.start?'active':''} onClick={()=>setStart(s.start)}>{formatDate(s.start,{dateStyle:undefined,timeStyle:'short'})}</button>)}</div>{start&&<div className="selection-summary"><Icon name="calendar"/>{formatDate(start)}</div>}</>}<div className="form-actions"><Button secondary onClick={()=>{setStep(0);setError('');}}>Back</Button><Button onClick={next} disabled={!start}>Continue</Button></div></>}
  {step===2&&<form onSubmit={submit} className="stack"><div className="selection-summary"><Icon name="calendar"/><div><strong>{services.find(s=>s.id===service)?.name}</strong><small>{formatDate(start)}</small></div><button type="button" className="text-link" onClick={()=>setStep(1)}>Change</button></div><Field label="Full name" id="patient-name" autoComplete="name" required maxLength={120} value={details.name} onChange={e=>change('name',e.target.value)}/><div className="form-grid"><Field label="Mobile number" id="patient-phone" type="tel" autoComplete="tel" required maxLength={32} placeholder="+14165550123" value={details.phone} onChange={e=>change('phone',e.target.value)}/><Field label="Email address" id="patient-email" type="email" autoComplete="email" required value={details.email} onChange={e=>change('email',e.target.value)}/></div><fieldset className="choice-field"><legend>Is this your first visit to Eyecon?</legend>{['yes','no'].map(v=><label key={v}><input type="radio" name="first-visit" required checked={details.firstVisit===v} onChange={()=>change('firstVisit',v)}/>{v==='yes'?'Yes':'No'}</label>)}</fieldset><details className="optional-fields"><summary>Insurance details <small>Optional</small></summary><div className="stack"><Field label="Insurance company" id="insurance" value={details.insurance} maxLength={120} onChange={e=>change('insurance',e.target.value)}/><Field label="Policy number" id="policy" value={details.policy} maxLength={120} onChange={e=>change('policy',e.target.value)} hint="Only clinic staff can see this information. You may bring your insurance card instead."/></div></details><details className="optional-fields"><summary>Designers you love <small>Optional</small></summary><Field label="Favourite brands" id="brands" placeholder="For example: Cartier, LINDBERG" value={details.brands} maxLength={300} onChange={e=>change('brands',e.target.value)}/></details><label className="checkbox-label"><input type="checkbox" checked={details.smsConsent} onChange={e=>change('smsConsent',e.target.checked)}/><span>Send me appointment reminders by SMS.<small>Optional. Message and data rates may apply. Contact the clinic to withdraw consent.</small></span></label><p className="privacy-note">{affiliate?'Your referrer can see your name and referral status. Your appointment type and insurance details stay with the clinic. ':''}Read our <Link href="/privacy">privacy notice</Link>.</p><div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this blank</label><input id="website" value={details.website} onChange={e=>change('website',e.target.value)} tabIndex={-1} autoComplete="off"/></div>{!DEMO&&<Captcha key={captchaKey} onToken={setCaptcha}/>}<div className="form-actions"><Button type="button" secondary onClick={()=>{setStep(1);setError('');}}>Back</Button><Button disabled={busy} type="submit">{busy?'Confirming…':'Confirm booking'}</Button></div></form>}
  {step===3&&confirmation&&<div className="confirmation"><div className="success-mark"><Icon name="check" size={35}/></div><p>We look forward to seeing you, {confirmation.booking.name.split(' ')[0]}.</p><div className="confirmation-card"><h3>{services.find(s=>s.id===confirmation.booking.service)?.name}</h3><p>{formatDate(confirmation.booking.start)}</p><p>{clinic.address||'Clinic location details will be confirmed by the team.'}</p><small>Booking reference: {confirmation.booking.id.slice(0,8).toUpperCase()}</small></div><h3>Add to your calendar</h3><div className="calendar-actions"><a className="button secondary" href={googleCalendar(confirmation.booking)} target="_blank" rel="noopener noreferrer">Google</a><button className="button secondary" onClick={()=>downloadFile(calendarFile(confirmation.booking),'eyecon-appointment.ics','text/calendar')}>Apple / .ics</button><a className="button secondary" href={outlookCalendar(confirmation.booking)} target="_blank" rel="noopener noreferrer">Outlook</a></div>{affiliate&&<Gift/>}<h3>Before your visit</h3><ul className="check-list">{instructions.map(t=><li key={t}><Icon name="check" size={18}/>{t}</li>)}</ul><Notice>{DEMO?'Demo booking saved in this browser. No email or SMS was sent.':confirmation.notifications?.email==='sent'?'Your confirmation email has been requested. Check your inbox.':'Your booking is saved. Email delivery is not available; keep your booking reference and calendar file.'}</Notice><Button secondary href={affiliate?'/book/'+affiliate.slug:'/'}>Return to Eyecon</Button></div>}
  </section></main><Footer/></>;
}
