'use client';
import { useEffect,useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { useApp } from './provider';
import { Header,Footer,Button,Icon,Gift,Referral,Loading,Notice } from './ui';
import { DEMO,services,brands,clinic } from '@/lib/config';
export default function Landing({slug}){
  const {data,ready}=useApp(),[affiliate,setAffiliate]=useState(null),[loaded,setLoaded]=useState(!slug),[error,setError]=useState(''),[floating,setFloating]=useState(false);
  useEffect(()=>{if(!slug)return;if(DEMO){if(!ready)return;const a=data.affiliates.find(a=>a.slug===slug&&a.active);setAffiliate(a||null);setLoaded(true);setError(a?'':'This referral page is no longer available.');}else{fetch('/api/availability?affiliate='+encodeURIComponent(slug)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setAffiliate(d.affiliate);}).catch(e=>setError(e.message)).finally(()=>setLoaded(true));}},[slug,data.affiliates,ready]);
  useEffect(()=>{if(!loaded||error)return;const hero=document.querySelector('.hero-actions .button'),final=document.querySelector('.final-cta .button');if(!hero||!final)return;let heroPast=false,finalVisible=false;const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.target===hero)heroPast=!entry.isIntersecting&&entry.boundingClientRect.top<0;if(entry.target===final)finalVisible=entry.isIntersecting;}setFloating(heroPast&&!finalVisible);});observer.observe(hero);observer.observe(final);return()=>observer.disconnect();},[loaded,error]);
  const booking=affiliate?'/booking?affiliate='+encodeURIComponent(affiliate.slug):'/booking';
  if(!loaded)return <Loading/>;
  if(error)return <><Header/><main className="container empty-page" id="main-content"><h1>Your introduction to Eyecon</h1><Notice error>{error}</Notice><Button href="/booking">Book directly</Button></main><Footer/></>;
  return <><Header bookingHref={booking}/><main id="main-content">
    <section className="hero"><div className="hero-copy">{affiliate?<Referral affiliate={affiliate}/>:<p className="eyebrow">PERSONAL EYE CARE · LUXURY EYEWEAR</p>}<h1>Exceptional vision.<br/><em>{affiliate?'Personally introduced.':'Thoughtfully cared for.'}</em></h1><p className="hero-description">Expert eye care and thoughtfully selected luxury eyewear. A personal experience, from your first visit.</p>{affiliate&&<Gift/>}<div className="hero-actions"><Button href={booking}>Book your appointment</Button><a className="text-link" href="#patient-experiences">Patient experiences</a></div><p className="quiet">Choose a time online. We’ll take care of the rest.</p></div><div className="hero-photo"><Image src="/images/hero.webp" alt="A woman wearing refined optical frames" fill priority sizes="(max-width: 800px) 100vw, 50vw"/><span>VISION, WITH A PERSONAL TOUCH</span></div></section>
    <section className="designer-strip" aria-label="Featured eyewear designers"><p>A selection of our designers</p><div>{['Cartier','Tom Ford','LINDBERG','DITA'].map(b=><span className={'brand-'+b.toLowerCase().replace(' ','-')} key={b}>{b}</span>)}</div></section>
    <section className="section container" id="appointments"><div className="section-intro"><p className="eyebrow">YOUR VISIT</p><h2>Find the right appointment</h2><p>Start with the care you need. Select a service to see available times.</p></div><div className="service-grid">{services.map(s=><Link className="service-row" key={s.id} href={booking+(affiliate?'&':'?')+'service='+s.id}><Icon name={s.icon}/><div><h3>{s.name}</h3><p>{s.description}</p></div><span>Book</span></Link>)}<div className="service-row emergency"><Icon name="phone"/><div><h3>Urgent eye concerns</h3><p>Please contact the clinic so the team can guide your next step.</p></div>{clinic.phone?<a className="text-link" href={'tel:'+clinic.phone}>Call clinic</a>:<span className="muted">Phone pending</span>}</div></div></section>
    <section className="care-section"><div className="container care-layout"><div><p className="eyebrow">PEOPLE FIRST</p><h2>Care from people<br/>you can know</h2><p>Your appointment is a conversation as well as an examination. Our team makes room for your questions, comfort and individual needs.</p><Button href={booking} secondary>Arrange your visit</Button></div><div className="doctor-grid">{['doctor1','doctor2'].map((d,i)=><article className="doctor" key={d}><Image src={'/images/'+d+'.webp'} width={300} height={300} alt={'Concept portrait for doctor profile '+(i+1)} sizes="(max-width: 800px) 45vw, 23vw"/><h3>Meet your optometrist</h3><p>Doctor names, credentials and biographies will be supplied by the clinic.</p></article>)}</div></div></section>
    <section className="section container reassurance"><div><p className="eyebrow">A LITTLE REASSURANCE</p><h2>Questions about coverage?</h2><p>Bring your insurance card to your visit. The clinic will confirm accepted insurers and the details of your coverage.</p><details><summary>What should I bring?</summary><p>Your current glasses or contact lenses, photo ID and insurance card. Clinic-specific instructions will appear with your confirmation.</p></details></div><div id="patient-experiences"><p className="eyebrow">PATIENT EXPERIENCES</p><h2>Trust built through care</h2><p>Verified patient reviews and the clinic’s current rating will appear here when review access is connected.</p>{clinic.reviews&&<a className="text-link" href={clinic.reviews} target="_blank" rel="noopener noreferrer">Read verified Google reviews</a>}</div></section>
    <section className="final-cta"><div className="container"><p className="eyebrow">WE LOOK FORWARD TO MEETING YOU</p><h2>Let’s make time for your vision</h2><Button href={booking}>Book your appointment</Button>{affiliate&&<p>Your personal referral from {affiliate.name}</p>}</div></section>
  </main><Footer/><div className={`mobile-book ${floating?'visible':''}`}><Button href={booking}>Book appointment</Button></div></>;
}
