'use client';
import { useEffect,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import { DEMO } from '@/lib/config';
import { browserClient } from '@/lib/supabase';
import { useApp } from './provider';
import { Logo,Button,Field,Notice } from './ui';
export default function LoginForm(){const {demoSignIn,reload,reset}=useApp(),router=useRouter(),params=useSearchParams();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[resetting,setResetting]=useState(false);const settingPassword=params.get('set-password')||params.get('mode')==='reset';
  async function submit(e){e.preventDefault();setError('');setMessage('');setBusy(true);try{const client=browserClient();if(settingPassword){if(password.length<12)throw new Error('Use a password with at least 12 characters.');const {error}=await client.auth.updateUser({password});if(error)throw error;}else if(resetting){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/login?mode=reset'});if(error)throw error;setMessage('If this account exists, a reset link will arrive in your email.');return;}else{const {error}=await client.auth.signInWithPassword({email,password});if(error)throw new Error('Email or password was not recognised.');}const state=await reload();router.push(state.user.role==='staff'?'/admin':'/affiliate');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <main className="login-page" id="main-content"><div className="login-editorial"><Logo/><h1>Personal introductions.<br/><em>Meaningful connections.</em></h1><p>A workspace for the people who bring Eyecon’s approach to eye care to their community.</p></div><div className="login-panel"><p className="eyebrow">EYECON WORKSPACE</p><h2>{settingPassword?'Set your password':resetting?'Reset your password':'Welcome back'}</h2><p>{DEMO?'Explore the affiliate and staff experiences with sample data.':'Sign in to your affiliate or staff account.'}</p><Notice error>{error}</Notice><Notice>{message}</Notice>{DEMO?<div className="stack"><Button onClick={()=>{demoSignIn('affiliate');router.push('/affiliate');}}>Explore affiliate demo</Button><Button secondary onClick={()=>{demoSignIn('staff');router.push('/admin');}}>Explore staff demo</Button><button className="text-link" onClick={()=>{reset();setMessage('Sample data has been restored.');}}>Reset demo data</button><small>Demo records stay in this browser. No email or SMS is sent.</small></div>:<form onSubmit={submit} className="stack">{!settingPassword&&<Field label="Email address" id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/>} {!resetting&&<Field label={settingPassword?'New password':'Password'} id="password" type="password" autoComplete={settingPassword?'new-password':'current-password'} required minLength={settingPassword?12:1} value={password} onChange={e=>setPassword(e.target.value)}/>}<Button disabled={busy} type="submit">{busy?'Please wait…':settingPassword?'Save password':resetting?'Send reset link':'Sign in'}</Button>{!settingPassword&&<button type="button" className="text-link" onClick={()=>{setResetting(!resetting);setError('');}}>{resetting?'Back to sign in':'Forgot your password?'}</button>}</form>}</div></main>;
}
