'use client';
import Link from 'next/link';
import Image from 'next/image';
import { useEffect,useRef } from 'react';
import { clinic,DEMO } from '@/lib/config';
export function Icon({name='eye',size=24}){const paths={eye:<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,circle:<><circle cx="12" cy="12" r="8"/><path d="m5 18 13-13"/></>,drop:<path d="M12 2S5 10 5 15a7 7 0 0 0 14 0c0-5-7-13-7-13Z"/>,people:<><circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2 21v-3a6 6 0 0 1 12 0v3m2-7a5 5 0 0 1 6 5v2"/></>,scan:<><path d="M3 8V3h5m8 0h5v5M3 16v5h5m8 0h5v-5M6 12h12"/><circle cx="12" cy="12" r="3"/></>,glasses:<><circle cx="6" cy="14" r="4"/><circle cx="18" cy="14" r="4"/><path d="M10 14h4M2 14l2-7m18 7-2-7"/></>,phone:<path d="M5 3h4l2 5-3 2a16 16 0 0 0 6 6l2-3 5 2v4c0 2-3 3-5 2A22 22 0 0 1 3 8c-1-2 0-5 2-5Z"/>,gift:<><path d="M3 9h18v4H3zM5 13v8h14v-8M12 9v12"/><path d="M12 9C4 9 5 1 9 4l3 5c8 0 7-8 3-5l-3 5Z"/></>,check:<path d="m5 12 4 4L20 5"/>,menu:<path d="M3 6h18M3 12h18M3 18h18"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.eye}</svg>;}
export function Logo(){return <Link href="/" className="logo" aria-label="Eyecon Optometry home"><span>EYECON</span><small>OPTOMETRY</small></Link>;}
export function Button({children,href,secondary=false,className='',...props}){const classes=`button ${secondary?'secondary':''} ${className}`;return href?<Link className={classes} href={href} {...props}>{children}</Link>:<button className={classes} {...props}>{children}</button>;}
export function Header({bookingHref='/booking',bookingLabel='Book appointment'}){return <header className="site-header"><div className="header-inner"><Logo/><div className="header-actions">{clinic.phone?<a className="call-link" href={'tel:'+clinic.phone}><Icon name="phone" size={19}/><span>{clinic.phone}</span></a>:<span className="header-note">Personal eye care</span>}<Button href={bookingHref}>{bookingLabel}</Button></div></div></header>;}
export function PreviewBar(){return DEMO?<div className="preview-bar">Design preview · Use fictional patient details.<Link href="/login">Explore workspaces</Link></div>:null;}
export function Referral({affiliate}){return affiliate?<div className="referral"><img src={affiliate.photo||'/images/affiliate.webp'} width="46" height="46" alt=""/><div><small>Your personal referral from</small><strong>{affiliate.name}</strong></div></div>:null;}
export function Gift({compact=false}){return <div className={`gift ${compact?'compact':''}`}><Icon name="gift" size={24}/><div><strong>$50 referral gift card</strong><small>Subject to the clinic’s confirmed eligibility terms.</small></div></div>;}
export function Footer(){return <footer className="footer"><Logo/><div>{clinic.address&&<p>{clinic.address}</p>}{clinic.hours&&<p>{clinic.hours}</p>}{clinic.phone&&<a href={'tel:'+clinic.phone}>{clinic.phone}</a>}{clinic.email&&<a href={'mailto:'+clinic.email}>{clinic.email}</a>}{!clinic.address&&<p>Clinic contact details will be added before launch.</p>}</div><div><Link href="/privacy">Privacy</Link><Link href="/login">Affiliate & staff sign-in</Link><small>© {new Date().getFullYear()} Eyecon Optometry</small></div></footer>;}
export function Field({label,id,error,hint,children,...props}){return <div className="field"><label htmlFor={id}>{label}</label>{children||<input id={id} aria-invalid={!!error} aria-describedby={hint?id+'-hint':undefined} {...props}/>} {hint&&<small id={id+'-hint'}>{hint}</small>}{error&&<small className="error-text">{error}</small>}</div>;}
export function Notice({children,error=false}){return children?<div role={error?'alert':'status'} className={`notice ${error?'error':''}`}>{children}</div>:null;}
export function Modal({open,title,onClose,children}){const ref=useRef(null);useEffect(()=>{const d=ref.current;if(open&&!d.open)d.showModal();if(!open&&d.open)d.close();},[open]);return <dialog ref={ref} className="modal" onCancel={onClose} onClose={onClose} aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title">{title}</h2><button onClick={onClose} className="icon-button" aria-label="Close dialog"><Icon name="close"/></button></div>{open&&children}</dialog>;}
export function Loading(){return <div className="loading" role="status"><span className="spinner"/>Loading your Eyecon experience…</div>;}
export function Portrait({src,alt,...props}){return <Image src={src} alt={alt} {...props}/>;}
