'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect,useMemo,useState } from 'react';
import { useApp } from './provider';
import { Logo,Button,Field,Notice,Loading,Modal,Icon } from './ui';
import { DEMO,services,statuses,sources,clinic,formatDate,money,serviceName,doctorName } from '@/lib/config';
import { giftNumber } from '@/lib/gift';
import { affiliateRows } from '@/lib/demo';
import { csv,validateBooking,validateSlug,slotTaken } from '@/lib/validation';
import { downloadFile } from '@/lib/calendar';
const affiliateNav=[['','Overview'],['referrals','Referrals'],['link','My link & QR'],['earnings','Earnings'],['profile','Profile']];
const staffNav=[['','Bookings'],['affiliates','Affiliates'],['leads','Leads'],['payouts','Payouts'],['messages','Messages']];
function QR({url}){const [image,setImage]=useState('');useEffect(()=>{let active=true;import('qrcode').then(m=>(m.default||m).toDataURL(url,{width:220,margin:2,color:{dark:'#202221',light:'#ffffff'},errorCorrectionLevel:'M'})).then(s=>{if(active)setImage(s);});return()=>{active=false;};},[url]);return image?<img className="qr" src={image} width="150" height="150" alt="QR code linking to this affiliate’s booking page"/>:<div className="qr" aria-label="Generating QR code"/>;}
function Empty({text='No records match your filters.'}){return <div className="empty-state"><Icon name="calendar" size={32}/><h3>{text}</h3><p>Your next update will appear here.</p></div>;}
export default function Workspace({role,section=''}){
  const app=useApp(),{data,user,ready,error:loadError,action,signOut,photo}=app,router=useRouter();
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[selected,setSelected]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[source,setSource]=useState('All'),[date,setDate]=useState(''),[view,setView]=useState('list'),[month,setMonth]=useState(new Date()),[detail,setDetail]=useState(null);
  const [origin,setOrigin]=useState(clinic.site);
  useEffect(()=>setOrigin(window.location.origin),[]);
  useEffect(()=>{if(ready&&!user&&!loadError)router.replace('/login');},[ready,user,loadError,router]);
  const own=data.affiliates.find(a=>a.id===user?.affiliateId);
  const rows=role==='affiliate'?affiliateRows(data.bookings,user?.affiliateId):data.bookings;
  const activeTitle=(role==='staff'?staffNav:affiliateNav).find(n=>n[0]===section)?.[1]||'Overview';
  const dayKey=d=>new Intl.DateTimeFormat('en-CA',{timeZone:clinic.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d));
  const filtered=rows.filter(b=>(!query||b.name.toLowerCase().includes(query.toLowerCase()))&&(status==='All'||b.status===status)&&(source==='All'||b.source===source)&&(!date||dayKey(b.start)===date));
  const eligible=rows.filter(b=>b.status==='Attended'&&b.commission>0&&b.payout==='Pending');
  const total=eligible.filter(b=>selected.includes(b.id)).reduce((s,b)=>s+b.commission,0);
  async function run(fn,success='Saved successfully.'){setBusy(true);setError('');setMessage('');try{const result=await fn();setMessage(success);return result;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
  async function save(act,payload,success){const result=await run(()=>action(act,payload),success);if(result!==false)setModal('');return result;}
  function exportRows(exported=filtered){const fields=role==='staff'?['name','email','phone','start','service','source','status','commission','payout']:['name','start','status','commission','payout'];downloadFile(csv(exported,fields),'eyecon-'+(section||'bookings')+'.csv','text/csv');setMessage('Your CSV download is ready.');}
  if(!ready)return <Loading/>;
  if(loadError)return <main className="container empty-page"><h1>Workspace unavailable</h1><Notice error>{loadError}</Notice><Button href="/login">Return to sign-in</Button></main>;
  if(!user)return <Loading/>;
  if(user.role!==role)return <main className="container empty-page"><h1>This workspace needs a different account</h1><Button href={user.role==='staff'?'/admin':'/affiliate'}>Open your workspace</Button></main>;
  const referralUrl=origin+'/book/'+own?.slug;
  function table(items,earnings=false){return items.length?<div className="table-wrap" tabIndex={0} role="region" aria-label={activeTitle+' table'}><table><caption className="sr-only">{activeTitle}</caption><thead><tr>{section==='payouts'&&<th scope="col">Select</th>}<th scope="col">Patient</th><th scope="col">{earnings?'Appointment':'Date & time'}</th>{role==='staff'&&<th scope="col">Source</th>}<th scope="col">Status</th>{earnings||role==='affiliate'?<><th scope="col">Commission</th><th scope="col">Payment</th></>:<th scope="col">Actions</th>}</tr></thead><tbody>{items.map(b=><tr key={b.id}>{section==='payouts'&&<td><input aria-label={'Select referral for '+b.name} type="checkbox" disabled={!(b.status==='Attended'&&b.commission>0&&b.payout==='Pending')} checked={selected.includes(b.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,b.id]:s.filter(id=>id!==b.id))}/></td>}<td><strong>{b.name}</strong>{role==='staff'&&b.affiliateId&&<small>{data.affiliates.find(a=>a.id===b.affiliateId)?.name||'Affiliate'}</small>}</td><td>{formatDate(b.start)}{role==='staff'&&<small>{serviceName(b.service)}</small>}</td>{role==='staff'&&<td>{b.source}</td>}<td>{role==='staff'&&!earnings?<select aria-label={'Status for '+b.name} value={b.status} disabled={busy} onChange={e=>run(()=>action('status',{id:b.id,status:e.target.value}),'Attendance updated.')}><option>{b.status}</option>{statuses.filter(s=>s!==b.status).map(s=><option key={s}>{s}</option>)}</select>:<span className={'badge '+b.status.toLowerCase()}>{b.status}</span>}</td>{earnings||role==='affiliate'?<><td>{role==='staff'&&section==='payouts'&&b.payout!=='Paid'?<form className="commission-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run(()=>action('commission',{id:b.id,amount:Number(form.get('amount'))}),'Commission approved.');}}><input type="number" name="amount" aria-label={'Commission for '+b.name} min="0" max="100000" step="0.01" defaultValue={b.commission} disabled={b.status!=='Attended'||!b.affiliateId}/><button className="text-link" disabled={busy||b.status!=='Attended'||!b.affiliateId}>Save</button></form>:money(b.commission)}</td><td><span className="badge">{b.payout}</span>{b.paidAt&&<small>{formatDate(b.paidAt,{timeStyle:undefined})}</small>}</td></>:<td><button className="text-link" onClick={()=>{setDetail(b);setModal('detail');}}>Details</button></td>}</tr>)}</tbody></table></div>:<Empty/>;}
  return <div className="workspace"><aside className="sidebar"><Logo/><p className="workspace-label">{role==='staff'?'CLINIC WORKSPACE':'AFFILIATE WORKSPACE'}</p><nav aria-label="Workspace navigation">{(role==='staff'?staffNav:affiliateNav).map(([path,label])=><Link key={path} href={'/'+(role==='staff'?'admin':'affiliate')+(path?'/'+path:'')} aria-current={path===section?'page':undefined}>{label}</Link>)}</nav><div className="sidebar-bottom"><Link href="/">View website</Link><button onClick={()=>run(async()=>{await signOut();router.push('/login');},'Signed out.')}>Sign out</button></div></aside><main className="workspace-main" id="main-content"><header className="workspace-header"><div><p className="eyebrow">{DEMO?'DEMO WORKSPACE':'EYECON WORKSPACE'}</p><h1>{role==='affiliate'&&!section?'Good morning, '+(own?.name.split(' ')[0]||'there'):activeTitle}</h1></div><div className="toolbar">{role==='staff'&&(!section||section==='leads')&&<><Button secondary onClick={()=>setModal('slot')}>Add available time</Button><Button onClick={()=>setModal('booking')}>New booking</Button></>}{role==='staff'&&section==='affiliates'&&<Button onClick={()=>setModal('affiliate')}>Add affiliate</Button>}{(section==='referrals'||section==='earnings'||section==='leads')&&<Button secondary onClick={()=>exportRows()}>Export CSV</Button>}</div></header><Notice error>{error}</Notice><Notice>{message}</Notice>
  {role==='affiliate'&&!section&&<><div className="stats">{[['Bookings this month',rows.filter(b=>{let d=new Date(b.start),now=new Date();return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();}).length],['Completed visits',rows.filter(b=>b.status==='Attended').length],['Pending commission',money(rows.filter(b=>b.payout==='Pending').reduce((s,b)=>s+b.commission,0))],['Paid',money(rows.filter(b=>b.payout==='Paid').reduce((s,b)=>s+b.commission,0))]].map(([label,value])=><article key={label}><p>{label}</p><strong>{value}</strong></article>)}</div><p className="quiet">{own?.commissionNote||'Commission terms will be confirmed by the clinic.'}</p><section className="referral-panel"><div><h2>Your personal referral link</h2><p className="link-value">{referralUrl}</p><Button onClick={()=>run(()=>navigator.clipboard.writeText(referralUrl),'Referral link copied.')}>Copy link</Button><Button secondary href="/affiliate/link">View QR code</Button></div><QR url={referralUrl}/></section><div className="section-heading"><h2>Recent referrals</h2><Link className="text-link" href="/affiliate/referrals">View all</Link></div>{table(rows.slice(0,5))}</>}
  {((role==='staff'&&(!section||section==='leads'))||section==='referrals')&&<><div className="filters"><Field label="Search patients" id="search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name"/><Field label="Status" id="status"><select id="status" value={status} onChange={e=>setStatus(e.target.value)}>{['All',...statuses].map(s=><option key={s}>{s}</option>)}</select></Field>{role==='staff'&&<Field label="Source" id="source"><select id="source" value={source} onChange={e=>setSource(e.target.value)}>{['All',...sources].map(s=><option key={s}>{s}</option>)}</select></Field>}<Field label="Date" id="date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="text-link" onClick={()=>{setQuery('');setStatus('All');setSource('All');setDate('');}}>Clear</button></div>{role==='staff'&&!section&&<div className="view-tabs"><button aria-pressed={view==='list'} onClick={()=>setView('list')}>List</button><button aria-pressed={view==='calendar'} onClick={()=>setView('calendar')}>Calendar</button><small>Times in {clinic.timezone}</small></div>}{view==='calendar'&&role==='staff'&&!section?<><div className="calendar-heading"><button className="button secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>Previous month</button><h2>{month.toLocaleDateString('en-CA',{month:'long',year:'numeric'})}</h2><button className="button secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>Next month</button></div><div className="month-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:new Date(month.getFullYear(),month.getMonth(),1).getDay()},(_,i)=><span key={'pad'+i}/>)}{Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>{const key=month.getFullYear()+'-'+String(month.getMonth()+1).padStart(2,'0')+'-'+String(i+1).padStart(2,'0');const count=rows.filter(b=>dayKey(b.start)===key).length;return <button key={key} onClick={()=>{setDate(key);setView('list');}} aria-label={key+', '+count+' bookings'}><span>{i+1}</span>{count>0&&<small>{count} bookings</small>}</button>;})}</div></>:table(filtered)}</>}
  {section==='link'&&own&&<section className="panel link-page"><p className="eyebrow">YOUR PERSONAL INTRODUCTION</p><h2>One link. A warm welcome.</h2><p>Share your link or QR code so each appointment connects back to your referral.</p><QR url={referralUrl}/><Field label="Your referral link" id="referral-url" readOnly value={referralUrl}/><div className="toolbar"><Button onClick={()=>run(()=>navigator.clipboard.writeText(referralUrl),'Referral link copied.')}>Copy link</Button><Button secondary onClick={()=>run(async()=>{const m=await import('qrcode');const url=await(m.default||m).toDataURL(referralUrl,{width:1000,margin:3});const a=document.createElement('a');a.href=url;a.download='eyecon-'+own.slug+'-qr.png';a.click();},'QR download ready.')}>Download QR</Button><Button secondary href={'mailto:?subject='+encodeURIComponent('Your introduction to Eyecon')+'&body='+encodeURIComponent('Book your Eyecon appointment through my personal link: '+referralUrl)}>Email link</Button><Button secondary href={'/book/'+own.slug}>Preview my page</Button></div></section>}
  {section==='earnings'&&<><div className="stats"><article><p>Pending commission</p><strong>{money(rows.filter(b=>b.payout!=='Paid').reduce((s,b)=>s+b.commission,0))}</strong></article><article><p>Paid commission</p><strong>{money(rows.filter(b=>b.payout==='Paid').reduce((s,b)=>s+b.commission,0))}</strong></article></div><p className="quiet">Amounts reflect commission approved by clinic staff.</p>{table(rows.filter(b=>b.commission>0),true)}</>}
  {section==='profile'&&own&&<Profile affiliate={own} busy={busy} onSave={p=>save('profile',p)} onPhoto={file=>run(()=>photo(file,own.id),'Photo updated.')}/>}
  {section==='affiliates'&&<div className="affiliate-grid">{data.affiliates.map(a=><article className="panel affiliate-card" key={a.id}><div className="affiliate-card-header"><img src={a.photo} alt={'Profile photo for '+a.name} width="60" height="60"/><div><h2>{a.name}</h2><p>{a.email}</p></div><span className="badge">{a.active?'Active':'Inactive'}</span></div><p>{a.bio||'No biography added yet.'}</p><div className="affiliate-link"><span>{origin+'/book/'+a.slug}</span><QR url={origin+'/book/'+a.slug}/></div><p className="quiet">{a.commissionRate}% reference rate. {a.commissionNote||'Commission approved manually.'}</p><div className="toolbar"><Button secondary href={'/book/'+a.slug}>Preview page</Button><Button secondary disabled={busy} onClick={()=>run(()=>action('toggle-affiliate',{id:a.id}),a.active?'Affiliate deactivated.':'Affiliate activated.')}>{a.active?'Deactivate':'Activate'}</Button></div><label className="upload-label">Update profile photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>2097152)setError('Use an image smaller than 2 MB.');else run(()=>photo(f,a.id),'Photo updated.');}}}/></label></article>)}</div>}
  {section==='payouts'&&<><div className="payout-summary"><div><h2>Approve commission, then record payment</h2><p>Enter an amount for attended referrals. Select the payments you have completed.</p></div><Button disabled={!selected.length||busy} onClick={()=>setModal('payout')}>Record {money(total)} as paid</Button></div><Notice>Recording a payout updates the ledger. It does not transfer money.</Notice>{table(rows.filter(b=>b.affiliateId),true)}</>}
  {section==='messages'&&<><p className="muted">Plain-text templates. Available fields: {'{name}, {date}, {address}, {phone}, {instructions}, {gift}'}.</p><div className="template-grid">{data.templates.map(t=><Template key={t.id} template={t} busy={busy} onSave={p=>save('template',p)}/>)}</div>{!DEMO&&<section className="panel"><h2>Recent delivery activity</h2>{data.jobs?.length?<ul className="delivery-list">{data.jobs.map((j,i)=><li key={i}><strong>{j.kind}</strong><span>{j.status}</span><small>{JSON.stringify(j.result)}</small></li>)}</ul>:<p>No message delivery activity yet.</p>}</section>}</>}
  </main><Modal open={!!modal} title={{booking:'New manual booking',affiliate:'Add affiliate',slot:'Add available appointment time',payout:'Record completed payments',detail:'Booking details'}[modal]||''} onClose={()=>setModal('')}><Notice error>{error}</Notice>{modal==='booking'&&<ManualForm affiliates={data.affiliates} slots={data.slots.filter(s=>new Date(s.start)>new Date()&&!slotTaken(s,data.bookings))} busy={busy} onSave={p=>{try{return save('booking',validateBooking(p,true),'Manual booking saved.');}catch(e){setError(e.message);}}}/>}{modal==='affiliate'&&<AffiliateForm busy={busy} onSave={p=>{try{validateSlug(p.slug);return save('affiliate',p,DEMO?'Affiliate created with a referral link and QR code.':'Affiliate created. An invitation email has been requested.');}catch(e){setError(e.message);}}}/>}{modal==='slot'&&<form className="stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const d=new Date(f.get('start'));save('slot',{start:d.toISOString(),duration:Number(f.get('duration'))},'Appointment time added.');}}><Field label="Start time (your browser’s local timezone)" id="slot-start" name="start" type="datetime-local" required/><Field label="Duration" id="duration"><select id="duration" name="duration">{[15,30,45,60,90].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></Field><p className="quiet">Add only times the clinic can honour. This calendar is independent of MyVisionExpress.</p><Button disabled={busy}>Add time</Button></form>}{modal==='payout'&&<div className="stack"><p>Record {selected.length} completed payments totalling <strong>{money(total)}</strong>?</p><p>This records an external payment as paid and updates the affiliate’s earnings.</p><Button disabled={busy} onClick={async()=>{const result=await save('payout',{ids:selected},'Payout recorded.');if(result!==false)setSelected([]);}}>Confirm paid</Button><Button secondary onClick={()=>setModal('')}>Cancel</Button></div>}{modal==='detail'&&detail&&<div className="booking-details"><dl>{[['Patient',detail.name],['Email',detail.email],['Phone',detail.phone],['Appointment',serviceName(detail.service)],['Time',formatDate(detail.start)],...(detail.preferredDoctor?[['Preferred optometrist',doctorName(detail.preferredDoctor)||detail.preferredDoctor]]:[]),['Source',detail.source],...(detail.giftCard?[['Gift card',giftNumber(data.affiliates.find(a=>a.id===detail.affiliateId),detail.giftCard.serial)+' · '+detail.giftCard.status+' · valid until '+formatDate(detail.giftCard.expiresAt,{timeStyle:undefined})]]:[]),['Insurance company',detail.insurance||'Not provided'],['Policy number',detail.policy||'Not provided'],['Favourite brands',detail.brands||'Not provided'],['SMS consent',detail.smsConsent?'Yes':'No']].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></div>}</Modal></div>;
}
function Profile({affiliate,busy,onSave,onPhoto}){return <form className="panel stack narrow-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:affiliate.id,name:f.get('name'),bio:f.get('bio')});}}><div className="profile-image"><img src={affiliate.photo} width="100" height="100" alt="Your affiliate profile photo"/><label>Profile photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f&&f.size<=2097152)onPhoto(f);}}/><small>JPG, PNG or WebP. Maximum 2 MB.</small></label></div><Field label="Display name" id="profile-name" name="name" defaultValue={affiliate.name} required maxLength={120}/><Field label="Short introduction" id="profile-bio"><textarea id="profile-bio" name="bio" defaultValue={affiliate.bio} maxLength={500} rows={5}/></Field><Button disabled={busy}>Save profile</Button></form>;}
function Template({template,busy,onSave}){return <form className="panel stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:template.id,subject:f.get('subject'),body:f.get('body')});}}><h2>{template.id.replaceAll('-',' ')}</h2><Field label="Email subject" id={template.id+'-subject'} name="subject" defaultValue={template.subject} required maxLength={150}/><Field label="Message" id={template.id+'-body'}><textarea id={template.id+'-body'} name="body" defaultValue={template.body} rows={6} maxLength={3000} required/></Field><Button disabled={busy}>Save template</Button></form>;}
function ManualForm({affiliates,slots,busy,onSave}){return <form className="stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:f.get('name'),email:f.get('email'),phone:f.get('phone'),service:f.get('service'),start:f.get('start'),source:f.get('source'),affiliateId:f.get('affiliateId')||null,firstVisit:f.get('firstVisit')==='yes',smsConsent:f.get('sms')==='on'});}}><div className="form-grid"><Field label="Patient name" id="manual-name" name="name" required/><Field label="Email" id="manual-email" name="email" type="email" required/><Field label="Mobile number" id="manual-phone" name="phone" type="tel" required/><Field label="Source" id="manual-source"><select name="source" id="manual-source">{['Phone','Walk-in','Direct'].map(s=><option key={s}>{s}</option>)}</select></Field></div><Field label="Credit an affiliate" id="manual-affiliate"><select id="manual-affiliate" name="affiliateId"><option value="">No affiliate</option>{affiliates.filter(a=>a.active).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field><Field label="Appointment type" id="manual-service"><select id="manual-service" name="service">{services.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="Available time" id="manual-start"><select id="manual-start" name="start" required><option value="">Choose a time</option>{slots.map(s=><option value={s.start} key={s.start}>{formatDate(s.start)}</option>)}</select></Field><Field label="First visit?" id="manual-first"><select id="manual-first" name="firstVisit"><option value="yes">Yes</option><option value="no">No</option></select></Field><label className="checkbox-label"><input type="checkbox" name="sms"/><span>The patient agreed to SMS reminders.</span></label><Button disabled={busy||!slots.length}>Save manual booking</Button></form>;}
function AffiliateForm({busy,onSave}){return <form className="stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:f.get('name'),email:f.get('email'),slug:f.get('slug'),bio:f.get('bio'),commissionRate:Number(f.get('rate')),commissionNote:f.get('note'),code:f.get('code')});}}><Field label="Full name" id="affiliate-name" name="name" required maxLength={120}/><Field label="Email address" id="affiliate-email" name="email" type="email" required/><Field label="Referral page name" id="affiliate-slug" name="slug" placeholder="alex-morgan" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={70} hint="Creates /book/alex-morgan and a matching QR code."/><Field label="Gift card code (optional)" id="affiliate-code" name="code" placeholder="AMO" pattern="[A-Za-z]{3}" maxLength={3} hint="Three letters used in their gift card numbers, for example EYC-AMO-••••••. Leave blank to use their initials."/><Field label="Short introduction" id="affiliate-bio"><textarea id="affiliate-bio" name="bio" rows={3} maxLength={500}/></Field><div className="form-grid"><Field label="Reference commission rate (%)" id="affiliate-rate" name="rate" type="number" defaultValue="0" min="0" max="100" step="0.01"/><Field label="Commission terms" id="affiliate-note" name="note" defaultValue="Terms awaiting approval" maxLength={300}/></div><p className="quiet">The rate is informational. Staff enter approved commission amounts after attendance. Upload a profile photo after creating the affiliate.</p><Button disabled={busy}>Create affiliate</Button></form>;}
